language: php
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - printf "\n" | pecl install yaml-beta
  - composer install

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  email: false
